#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu May 16 10:09:28 2019
This package is a merger of Elisabeth Koerts work (2018) and my own code 
from 2015-2017) created earlier about the small dendritic inputs.
It will contain a "reduced SBC model" (an SBC soma ball with a stick dendrite 
to study interaction of small and large phaselocked inputs in a reduced setting)
and "full SBC" model with a dendrite generated by 3D reconstruction.
These functions are used in various programs to generate results for the 2019 
SBC dendrite paper.
@author: kuenzel
"""
