#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/kuenzel/Programme/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/kuenzel/Programme/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/kuenzel/Dokumente/Python/smallexc/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
